### ISSUE TITLE
Cannot set Spacebar as a hotkey

### ISSUE THREAD

**Issue by Yaered** [timtwalsh/ClickCountR#1]
Currently, spacebar's functionality in the settings menu is to reset a keybind to "none". I use spacebar as one of my hotkeys (I'm sure plenty of other people do too), would appreciate if it can be set as one.

**Comment by Yaered** [comment]
Edit: found a workaround for this by directly editing the ClickCountR.ini file, ie: "Skill1=Space"

**Comment by timtwalsh** [comment]
Version 1.1+: Auto-configure keybinds should work for all in-game bindings. Workaround should no longer be nessisary (or possible)
